# Generated by Django 3.2.6 on 2021-09-07 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('display_picture', models.ImageField(upload_to='')),
                ('enrolment_number', models.IntegerField(default=0)),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('normal', 'normal')], default='normal', max_length=6)),
                ('online_status', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wiki', djrichtextfield.models.RichTextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('finished_status', models.BooleanField(default=False)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_creator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('finished_status', models.BooleanField(default=False)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='list_creator', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.project')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', djrichtextfield.models.RichTextField()),
                ('finished_status', models.BooleanField(default=False)),
                ('assignees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_creator', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.list')),
            ],
        ),
    ]
