# Generated by Django 3.2.6 on 2021-08-30 15:02

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('full_name', models.CharField(max_length=200)),
                ('display_picture', models.ImageField(upload_to='')),
                ('enrol_number', models.IntegerField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('normal', 'normal')], default='normal', max_length=6)),
                ('status', models.CharField(choices=[('ON', 'online'), ('OFF', 'offline')], default='OFF', max_length=3)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wiki', djrichtextfield.models.RichTextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('proj_status', models.BooleanField(default=False)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_creator', to='project_manager.user')),
                ('members', models.ManyToManyField(to='project_manager.user')),
            ],
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('list_status', models.BooleanField(default=False)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='list_creator', to='project_manager.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.project')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.user')),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', djrichtextfield.models.RichTextField()),
                ('card_status', models.BooleanField(default=False)),
                ('assignees', models.ManyToManyField(to='project_manager.user')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_creator', to='project_manager.user')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.list')),
            ],
        ),
    ]
