# Generated by Django 3.2.6 on 2021-08-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_status',
            new_name='finished_status',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='list_status',
            new_name='finished_status',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='proj_status',
            new_name='finished_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='enrol_number',
            new_name='enrollment_number',
        ),
    ]
