# Generated by Django 3.2.6 on 2021-09-07 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_alter_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='list_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
