# Generated by Django 3.2.6 on 2021-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_auto_20210831_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='online_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='enrollment_number',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='enrolment_number',
            field=models.IntegerField(default=0),
        ),
    ]
