# Generated by Django 3.2.6 on 2021-09-08 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_auto_20210907_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_manager.card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
