# Generated by Django 3.2.6 on 2021-09-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_alter_user_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='online_status',
            field=models.CharField(choices=[('ON', 'online'), ('OFF', 'offline')], default='OFF', max_length=3),
        ),
    ]
